# An example of Jekyll site
# using Bulma Material Design
# for personal learning purpose.

# -- -- -- -- -- # -- -- -- -- -- # -- -- -- -- --
# General Jekyll Setting

# Site settings
title: Your mission. Good Luck!
email: epsi.nurwijayadi@gmail.com
description: >- # description below
  Embrace, extend, and extinguish: Open Source with Daily Genuine Experience.
  From Coding, Design, Package Management Tweak to Desktop Customization.

# the subpath of your site, e.g. /blog
baseurl: "/circleci-jekyll" 

# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Jakarta

# the base hostname & protocol for your site, e.g. http://example.com
# This wil be shown in feed.xml
url: "http://localhost:4000"
twitter_username: nurwijayadi
github_username:  epsi-rns

# Build settings
markdown: kramdown
highlighter: rouge

# -- -- -- -- -- # -- -- -- -- -- # -- -- -- -- --
# Specific Jekyll Plugins

# all plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# jekyll-paginate-v1
# paginate: 2
# paginate_path: "pages/blog-:num"

# jekyll-paginate-v2
# Produces a cleaner folder structure when using categories
# permalink: /:year/:month/:title.html
permalink: /:categories/:year/:month/:day/:title:output_ext

# jekyll-paginate-v2
# Pagination Settings
pagination:
  enabled      : true
  per_page     : 2
  permalink    : '/blog-:num/'
  title        : ':title | :num of :max pages'
  limit        : 0
  sort_field   : 'date'
  sort_reverse : true

# jekyll-paginate-v2
autopages:
  disabled: false

# -- -- -- -- -- # -- -- -- -- -- # -- -- -- -- --
# Custom Tailor Made Seetings

#opengraph
locale: en_US
logo: /assets/images/logo-gear-opengraph.png

# External Services, leave blank to ignore or put true to use
service:
  google_analytics_key: false
  disqus_key: false  
  google_adsense: false
